Form/GroupedFormView.php
<?php

namespace Zenstruck\Bundle\FormBundle\Form;

use Symfony\Component\Form\Form;
use Symfony\Component\Form\FormView;

/**
 * @author Kevin Bond <kevinbond@gmail.com>
 */
class GroupedFormView
{
    protected $groups = array();
    protected $data = array();
    protected $form;

    /**
     * @param Form|FormView $form
     * @param string        $defaultGroup
     * @param array         $order
     */
    public function __construct($form, $defaultGroup = 'Default', $order = array())
    {
        if ($form instanceof Form) {
            $form = $form->createView();
        }

        $this->form = $form;

        // use custom order
        foreach ($order as $item) {
            $this->groups[$item] = array();
        }

        // if no order is set, make default first group
        if (empty($this->groups)) {
            $this->groups[$defaultGroup] = array();
        }

        // add fields to groups
        $this->setGroupsFromForm($this->form->children, $defaultGroup);
        // filter empty groups
        $this->groups = array_filter($this->groups, function ($fields) {
                return count($fields);
            });

    }

    public function getForm()
    {
        return $this->form;
    }

    public function isValid($group = null)
    {
        if (!$group) {
            return $this->form->vars['valid'];
        }

        $valid = true;

        foreach ($this->groups[$group] as $field) {
            if (!$field->vars['valid']) {
                $valid = false;
            }
        }

        return $valid;
    }

    public function getGroupNames()
    {
        return array_keys($this->groups);
    }

    public function getGroups()
    {
        return $this->groups;
    }

    public function setData($name, $value)
    {
        $this->data[$name] = $value;
    }

    public function getData($name, $default = null)
    {
        if (!$this->hasData($name)) {
            return $default;
        }

        return $this->data[$name];
    }

    public function hasData($name)
    {
        return array_key_exists($name, $this->data);
    }

    public function getVars()
    {
        return $this->form->vars;
    }

    public function setGroupsFromForm($form, $defaultGroup)
    {
        foreach ($form as $field) {
            if ($field->vars['group']) {
                $group = $field->vars['group'];
            } elseif ($field->parent && $field->parent->vars['group']) {
                $group = $field->parent->vars['group'];
            } else {
                $group = $defaultGroup;
            }

            $this->groups[$group][] = $field;
        }
    }
}

Resources/views/Twitter/form_bootstrap3_layout.html.twig
{% extends 'form_div_layout.html.twig' %}

{% block widget_attributes %}
    {% if type is defined and type != 'hidden' %}
        {% set attr = attr|merge({'class': (attr.class|default('') ~ ' form-control')|trim}) %}
    {% endif %}

    {{ parent() }}
{% endblock widget_attributes %}

{% block form_row %}
    <div class="form-group{% if errors|length > 0 %} has-error{% endif %}">
        {{ form_label(form, label|default(null)) }}
        {% set ctrl_width = theme_options.control_width is defined ? theme_options.control_width : 'col-md-10' %}
        <div class="{{ ctrl_width }}">
            {{ form_widget(form) }}
            {{ form_errors(form) }}
            {% if help is defined and help %}
                <div class="help-block">{{ help }}</div>
            {% endif %}
        </div>
    </div>
{% endblock form_row %}

{% block money_widget %}
    {% set currency = money_pattern|replace({'{{ widget }}': ''})|trim %}

    {% if currency %}
        <div class="input-group">
            <span class="input-group-addon">{{ currency }}</span>
            {{ block('form_widget_simple') }}
        </div>
    {% else %}
        {{ money_pattern|replace({ '{{ widget }}': block('form_widget_simple') })|raw }}
    {% endif %}
{% endblock money_widget %}

{% block checkbox_widget %}
    {% if 'choice' not in form.parent.vars.block_prefixes %}
        {% set attr = attr|merge({'class': (attr.class|default('') ~ ' control-standalone')|trim}) %}
    {% endif %}
    {{ parent() }}
{% endblock checkbox_widget %}

{% block choice_widget_expanded %}
    <div {{ block('widget_container_attributes') }}>
        {% for child in form %}
            {{ form_label(child) }}
        {% endfor %}
    </div>
{% endblock choice_widget_expanded %}

{% block choice_widget_collapsed %}
    {% set type = 'select' %}
    {{ parent() }}
{% endblock choice_widget_collapsed %}

{% block form_label %}
    {% set is_multichoice_widget = (checked is defined) and ('choice' in form.parent.vars.block_prefixes) %}

    {% if is_multichoice_widget %}
        {% set label_attr = label_attr|merge({'class': 'radio' in block_prefixes ? 'radio' : 'checkbox'}) %}
    {% else %}
        {% set lbl_width = theme_options.label_width is defined ? theme_options.label_width : 'col-md-2' %}
        {% set label_attr = label_attr|merge({'class': 'control-label ' ~ lbl_width}) %}
    {% endif %}
    {% if not compound %}
        {% set label_attr = label_attr|merge({'for': id}) %}
    {% endif %}
    {% if required %}
        {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' required')|trim}) %}
    {% endif %}
    {% if label is empty %}
        {% set label = name|humanize %}
    {% endif %}
    <label{% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}>
        {{ label|trans({}, translation_domain) }}
        {% if is_multichoice_widget %}
            {{ form_widget(form) }}
        {% endif %}
    </label>
{% endblock form_label %}

{% block collection_widget %}
    {% import _self as macros %}
    {% if prototype is defined %}
        {% set attr = attr|merge({'data-prototype': block('collection_prototype') }) %}
    {% endif %}
    <div {{ block('widget_container_attributes') }}>
        {{ form_errors(form) }}
        <div class="form-collection{{ form|length ? '' : ' hide' }}">
            {% for rows in form %}
                {{ macros.collection_field(rows, allow_delete) }}
            {% endfor %}
        </div>
        {{ form_rest(form) }}
    </div>
    {% if allow_add %}
        <a href="#" class="btn btn-info form-collection-add">Add</a>
    {% endif %}
{% endblock collection_widget %}

{% block collection_prototype %}
    {% import _self as macros %}
    {{ macros.collection_field(prototype, allow_delete) }}
{% endblock collection_prototype %}

{% macro collection_field(rows, allow_delete) %}
    <div class="form-collection-element">
        {% for row in rows %}
            {{ form_row(row) }}
        {% endfor %}
        {% if allow_delete %}
            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                    <a class="btn btn-danger remove" href="#">Delete</a>
                </div>
            </div>
        {% endif %}
    </div>
{% endmacro %}

{% block form_errors %}
    {% if errors|length > 0 %}
        <span class="help-block">
            {% for error in errors %}
                {{ error.message }}
            {% endfor %}
        </span>
    {% endif %}
{% endblock form_errors %}

{% block zenstruck_ajax_entity_widget %}
    {% set type = 'hidden' %}
    <input type="{{ type }}" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
{% endblock %}

{% block zenstruck_tunnel_entity_widget %}
    <input type="hidden" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
    <div class="input-group zenstruck-tunnel-widget">
        <input type="text" disabled="disabled" value="{{ title }}" class="form-control zenstruck-tunnel-title" />
        <span class="input-group-btn">
            {% if not required %}
                <a href="#" class="btn btn-default zenstruck-tunnel-clear"><span class="glyphicon glyphicon-remove"></span></a>
            {% endif %}
            <a href="#" class="btn btn-default zenstruck-tunnel-select"{% if callback %} data-callback="{{ callback }}"{% endif %}>{{ button_text|trans }}</a>
        </span>
    </div>
{% endblock %}

{% block textarea_widget -%}
    {% set type = 'textarea' %}
    {{ parent() }}
{%- endblock textarea_widget %}

Resources/views/Twitter/form_bootstrap_layout.html.twig
{% extends 'form_div_layout.html.twig' %}

{% block form_row %}
    <div class="control-group {% if errors|length > 0 %}error{% endif %}">
        {{ form_label(form, label|default(null)) }}
        <div class="controls">
            {{ form_widget(form) }}
            {{ form_errors(form) }}
            {% if help is defined and help %}
                <div class="help-block">{{ help }}</div>
            {% endif %}
        </div>
    </div>
{% endblock form_row %}

{% block money_widget %}
    {% set currency = money_pattern|replace({'{{ widget }}': ''})|trim %}

    {% if currency %}
        <div class="input-prepend">
            <span class="add-on">{{ currency }}</span>
            {{ block('form_widget_simple') }}
        </div>
    {% else %}
        {{ money_pattern|replace({ '{{ widget }}': block('form_widget_simple') })|raw }}
    {% endif %}
{% endblock money_widget %}

{% block checkbox_widget %}
    {% if 'choice' not in form.parent.vars.block_prefixes %}
        {% set attr = attr|merge({'class': (attr.class|default('') ~ ' control-standalone')|trim}) %}
    {% endif %}
    {{ parent() }}
{% endblock checkbox_widget %}

{% block choice_widget_expanded %}
    <div {{ block('widget_container_attributes') }}>
        {% for child in form %}
            {{ form_label(child) }}
        {% endfor %}
    </div>
{% endblock choice_widget_expanded %}

{% block form_label %}
    {% set is_multichoice_widget = (checked is defined) and ('choice' in form.parent.vars.block_prefixes) %}

    {% if is_multichoice_widget %}
        {% set label_attr = label_attr|merge({'class': 'radio' in block_prefixes ? 'radio' : 'checkbox'}) %}
    {% else %}
        {% set label_attr = label_attr|merge({'class': 'control-label'}) %}
    {% endif %}
    {% if not compound %}
        {% set label_attr = label_attr|merge({'for': id}) %}
    {% endif %}
    {% if required %}
        {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' required')|trim}) %}
    {% endif %}
    {% if label is empty %}
        {% set label = name|humanize %}
    {% endif %}
    <label{% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}>
        {{ label|trans({}, translation_domain) }}
        {% if is_multichoice_widget %}
            {{ form_widget(form) }}
        {% endif %}
    </label>
{% endblock form_label %}

{% block collection_widget %}
    {% import _self as macros %}
    {% if prototype is defined %}
        {% set attr = attr|merge({'data-prototype': block('collection_prototype') }) %}
    {% endif %}
    <div {{ block('widget_container_attributes') }}>
        {{ form_errors(form) }}
        <div class="form-collection{{ form|length ? '' : ' hide' }}">
            {% for rows in form %}
                {{ macros.collection_field(rows, allow_delete) }}
            {% endfor %}
        </div>
        {{ form_rest(form) }}
    </div>
    {% if allow_add %}
        <a href="#" class="btn btn-info form-collection-add">Add</a>
    {% endif %}
{% endblock collection_widget %}

{% block collection_prototype %}
    {% import _self as macros %}
    {{ macros.collection_field(prototype, allow_delete) }}
{% endblock collection_prototype %}

{% macro collection_field(rows, allow_delete) %}
    <div class="form-collection-element">
        {% for row in rows %}
            {{ form_row(row) }}
        {% endfor %}
        {% if allow_delete %}
            <div class="form-actions">
                <a class="btn btn-danger remove" href="#">Delete</a>
            </div>
        {% endif %}
    </div>
{% endmacro %}

{% block form_errors %}
    {% if errors|length > 0 %}
        <span class="help-inline">
            {% for error in errors %}
                {{ error.message }}
            {% endfor %}
        </span>
    {% endif %}
{% endblock form_errors %}

{% block zenstruck_ajax_entity_widget %}
    <input type="hidden" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
{% endblock %}

{% block zenstruck_tunnel_entity_widget %}
    <div class="input-append zenstruck-tunnel-widget">
        <input type="hidden" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
        <span class="uneditable-input zenstruck-tunnel-title">{{ title }}</span>
        {% if not required %}
            <a href="#" class="btn zenstruck-tunnel-clear"><b class="icon-remove"></b></a>
        {% endif %}
        <a href="#" class="btn zenstruck-tunnel-select"{% if callback %} data-callback="{{ callback }}"{% endif %}>{{ button_text|trans }}</a>
    </div>
{% endblock %}

Resources/views/Twitter/grouped_form.html.twig
<ul class="nav nav-tabs">
    {% block tabs_header %}
        {% for name in grouped_form.groupNames %}
            <li{{ loop.first ? ' class="active"' : null }}>
                <a class="{{ not grouped_form.valid(name) ? 'text-error' : null }}" href="#{{ name|slugify }}" data-toggle="tab">{{ name }}</a>
            </li>
        {% endfor %}
    {% endblock %}
</ul>

<div class="tab-content">
    {% block tabs_content %}
        {% for name, group in grouped_form.groups %}
            <div class="tab-pane{{ loop.first ? ' active' : null }}" id="{{ name|slugify }}">
                {% for field in group %}
                    {{ form_row(field) }}
                {% endfor %}
            </div>
        {% endfor %}
    {% endblock %}
</div>